export const excludedTeams = [
  "Atlanta Thrashers",
  "Hartford Whalers",
  "Minnesota North Stars",
  "Quebec Nordiques",
  "Winnipeg Jets (1979)",
  "Colorado Rockies",
  "Ottawa Senators (1917)",
  "Hamilton Tigers",
  "Pittsburgh Pirates",
  "Philadelphia Quakers",
  "Detroit Cougars",
  "Montreal Wanderers",
  "Quebec Bulldogs",
  "Montreal Maroons",
  "New York Americans",
  "St. Louis Eagles",
  "Oakland Seals",
  "Atlanta Flames",
  "Kansas City Scouts",
  "Cleveland Barons",
  "Detroit Falcons",
  "Brooklyn Americans",
  "California Golden Seals",
  "Toronto Arenas",
  "Toronto St. Patricks",
  "NHL",
];
